### ISSUE TITLE
NPC field should be deprecated and replaced with Villain

### ISSUE THREAD

**Issue by MattColville** [AdventureLookup/AdventureLookup#109] opened 2017-08-07 06:17 UTC
I'm not sure what the "NPC" field is doing, as far as I can tell, only one adventure is using it, and no one's ever going to search for "all adventures featuring Tarren Traskar."

Folks have asked for a boss monster field, and they expect it to have stuff like Strahd in it, but I think the general use case will be "show me all adventures with a Beholder as the boss monster." Not, like, a specific named beholder.

So, absolutely we need a Villain field, maybe "Boss Monster" would be better, as it more directly communicated "this is the thing pulling the strings." And it should allow monsters. 

The text for Boss Monster should read "The species of the ultimate villain of the adventure, if there is one."

Meanwhile, I think it's safe to assume that if a famous NPC like Strahd appears in an adventure, his name will be in the description. Or should be!

I just want to avoid a scenario like we have with the current NPC list where it's a ton of named characters no one's ever heard of and whom don't appear in any other adventures.

**Comment by Bundy169** [comment] 2017-08-07 10:43
I think you're on the right track with the BBEG, however I think the BBEG, NPC's and Monsters need their own fields. BBEG also needs to be spelled out in the description for the field (Big Bad Evil Guy/Girl/Thing).

Kalarel the Vile doesn't appear in the description of Keep on the Shadowfell so should be added as the Boss Monster? 

Agree the NPC's should probably be only notable ones but how many NPC's are going to be in multiple modules anyway? (although Tarren Traskar is super cool he ** spoiler ** doesn't make it to the end of the adventure.) But it might be cool just to be able to list all the Villians/BBEG's/Boss Monsters by name and go "Oooh, that's an interesting name. I'll have a look to see what he/she/it is."

There is already the ability in the BBEG field to tag it as Unique if it is named and add a type of monster, but this doesn't appear anywhere. This may be redundant anyway because if the BBEG is a monster the type of monster would be added in the Monster field.

**Comment by harkenn** [comment] 2017-08-07 15:06
Spoke with @cmfcmf in discord on this, NPCs definitely need to go away. The only other question is whether to lump "Villains" in with "Monsters" for which there is no clear winner and the decision will at least partially be arbitrary. However it displays, however, the only reasonable solution in the data-model and the storage is to store "Villains" as a Monster with `isUnique` set to `true`. Villains are - after all - simply more powerful versions of their run-of-the-mill brethren. 

For NPCs, if we chose to split `Villains` out into its own display field (remember, its still stored as a `Monster`) then we might choose to make that display field be `Villains / Notable NPCs` to account for the few adventures that do have notable NPCs.

**Comment by cmfcmf** [comment] 2017-08-07 16:22
Going to work on this now.

**Comment by calculuschild** [comment] 2017-08-07 21:32
If I can chime in here, I want to throw in my support that if there is a Villain/BBEG field, the main goal should be to show what monster type it is, not the name of the NPC. I don't think anybody coming to the site is going to say "I need an adventure where the main bad guy is named Steve." They are going to say, "I need an adventure where the main bad guy is a Necromancer. Look, here's a nice big list. Let's look at one. Oh, cool, the Necromancer in this one is named Steve."

I feel like there should be two fields there: a BBEG species box that works identically to the other monster box, and an optional BBEG name that would appear in parentheses under the BBEG species when you look at the adventure. 

On this note, I also think a similar issue is happening with "Notable Items." We have tons of named, unique items that nobody will recognize, making the entire field useless. Perhaps there needs to be a general list of item types (Magic daggers, magic swords, magic plate armor, etc.) and an optional sub-field with the item name. Because, again, nobody is going to search for all adventures with the "Aurumvorax Kidneys," but they might search "monster parts."

**Comment by etchalon** [comment] 2017-08-07 21:36
I tend to believe, when capturing data, it's better to capture as much as possible and figure out ways to normalize it in the UX, or programatically.

For NPCs, I'd think classifying the NPC's monster type would add depth to the amount of data (and if done right, would result in a great secondary database)

For Notable Items, I'd offer the same solution. If we think we should classify items by what type of item they are, find a way to let people both name the item, and classify it (and if done right, would result in a great secondary database).

We seem to making a lot of a "nobody will ever do X" statements, without enough data from the field to make those calls.

**Comment by MattColville** [comment] 2017-08-07 22:27
People can't search for things they don't know exist. I think we can accept that as an axiom.

The goal of AL.com is to help DM's find an adventure that suits their needs. If an adventure has a unique item or character, then by definition folks aren't going to look for it. Because they don't know it exists.

But I absolutely do believe people will want to know stuff like "Has the Sword of Kas ever appeared in an adventure, and if so which one?" Or "I think it would be cool if my players found a Crystal Ball, which adventures do they appear in?"

The mistake curators are making is to think detail is the same as usefulness and I don't believe that's the case. DMs want to know stuff like "Which adventures feature a Beholder as the villain?" That is something I have seen people ask online for 20 years, I know there's demand for that kind of stuff, and my goal with AL.com is to empower those people.

Whereas I don't believe the "Which adventures feature Tarren Traskar" users are out there, and I want to focus on **clearly** providing answers for the users I know exist. 

AL.com is not an encyclopedia. It's not a catalog of every NPC and every item in every adventure. It's a database for finding the adventure that suits your needs and I feel like I have a pretty good idea what those needs are.

To the extent that I might be wrong, getting this stuff right is going to empower the vast majority of users, so I want to focus on that stuff now.

**Comment by harkenn** [comment] 2017-08-07 22:38
@mattcolville do we want to handle `has beholder as villain` as well as the standard `has beholder at all `?

**Comment by calculuschild** [comment] 2017-08-08 17:29
In the case of Boss Monsters, it seems like the next step is to remove all the NPC names from the search options.

**Comment by MattColville** [comment] 2017-08-08 18:55
Absolutely. There's a substantive and meaningful difference between "has" and "features." At all levels of play. In fact I think the "features" Bad Guy field is the more important. DM's tend to want "an adventure where you assault a goblin den" Or a Dragon Lair, than merely "has goblins in it." Or a dragon.

In other words, choosing the villain of the piece had a big impact on the tone of the adventure, whereas "there are goblins in here" tells you much less.

**Comment by cmfcmf** [comment] 2017-08-12 08:42
Alright, looks like we can close this as well. If there still is an adventure with a random NPC listed as villain, create a change request for the specific adventure and either the author or a curator can remove the NPC-villain.

**Closed by cmfcmf** 2017-08-12 08:42 UTC
Labels: enhancement, fixed in dev

**Comment by calculuschild** [comment] 2017-08-12 15:40
I just want to be sure this is working as intended. When I look at the Boss Monsters search box, I see *only* NPC names. I can find Explicita Defilus in the list, but I can't search boss monsters who are a Spirit Naga. This seems backward from what @MattColville wanted (correct me if I'm wrong.)

**Comment by MattColville** [comment] 2017-08-12 20:23
It's 100% backwards. 

The video (which I'm making today I think!) will go into detail about how all the fields are intended to work and that, I think, will do a lot to help the site grow in the manner I intended.

So I'll explain that the Villain/Boss Monster field is for people looking for "An adventure with a beholder as the bad guy." Since they _by definition_ don't know the name of the beholder in I, Tyrant. If they did, they wouldn't need Adventure Lookup!

I can imagine a scenario where folks are looking for "adventures featuring Strahd" and that's fine. Strahd, Orcus, these guys are fine to have in there. But Vampire, and Demon also need to be in there.

Folks I think naturally want to treat AL.com as an encyclopedia, but it's not. It's a catalog. Catalogs help people buy things, they don't list every single part.
